stages:
  - name: prepslha
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/prepare_slha'}
      parameters:
        template: /templates/slha_template.slha
        stop_mass: {stages: init, output: stop_mass, unwrap: true}
        neutralino_mass: {stages: init, output: neutralino_mass, unwrap: true}
        outputSLHA: '{workdir}/spectrum.slha'

  - name: herwig
    dependencies: ['prepslha']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/herwig'}
      parameters:
        slhafile: {stages: prepslha, output: outputSLHA, unwrap: true}
        events: {stages: init, output: events, unwrap: true}
        seed: 1234
        hepmcfile: '{workdir}/out.hepmc'
        herwigruncard: '{workdir}/runcard.dat'
  - name: compute_xsec
    dependencies: ['init']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/compute_xsec'}
      parameters:
        stop_mass: {stages: init, output: stop_mass, unwrap: true}
        xsecfile: '{workdir}/xsec.json'
  - name: checkmate
    dependencies: ['compute_xsec','herwig']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/checkmate'}
      parameters:
        seed: 9876
        outputdir: '{workdir}/checkmaterun'
        xsecfile: {stages: compute_xsec, output: xsecfile, unwrap: true}
        hepmcfile: {stages: herwig, output: hepmcfile, unwrap: true}
        analysis: {stages: init, output: analysis, unwrap: true}
        runcardfile: '{workdir}/checkmate.dat'
  - name: format_results
    dependencies: ['checkmate']
    scheduler:
      scheduler_type: singlestep-stage
      step: {$ref: 'steps.yml#/format_results'}
      parameters:
        outputdir: {stages: checkmate, output: outputdir, unwrap: true}
        analysis: {stages: init, output: analysis, unwrap: true}
        limitresultfile: '{workdir}/limits.json'
